tunnel: 9a59e21c-7e0d-4cac-8502-59bc66436e0f
credentials-file: /etc/cloudflared/creds.json

ingress:
  - hostname: visionflow.info
    service: http://localhost:4000
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      keepAliveConnections: 100
      keepAliveTimeout: 60s
      tcpKeepAlive: 60s
      httpHostHeader: visionflow.info

  - service: http_status:404

# Logging
logLevel: debug
transport-loglevel: debug

# Connection settings
protocol: quic
noAutoupdateFrequency: true
