version: '3.8'

services:
  webxr-graph:
    build: .
    ports:
      - "8080:8080"  # Application port
    environment:
      - RUST_LOG=info
      - BIND_ADDRESS=0.0.0.0
      - PORT=8080
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: sh -c "/app/start.sh"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - webxr-graph
