version: '3.8'

services:
  webxr-graph:
    build: .
    ports:
      - "8443:8443"
    environment:
      - RUST_LOG=info
      - BIND_ADDRESS=0.0.0.0
      - PORT=8080
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./ssl:/etc/nginx/ssl
    command: sh -c "service nginx start && /app/webxr-graph"
