name: logseq-xr

services:
  webxr-graph:
    build: .
    image: logseq-xr-image:latest
    container_name: logseq-xr-webxr-graph-1
    read_only: false
    networks:
      - logseq_net
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 64G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "4000:4000"
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - BIND_ADDRESS=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./settings.toml:/app/settings.toml:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 4G
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: logseq-xr-tunnel-1
    networks:
      - logseq_net
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml:ro
    depends_on:
      webxr-graph:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "5"

networks:
  logseq_net:
    driver: bridge
