# settings.toml

# Prompt for the AI assistant
prompt = """
You are an AI assistant building summaries of web links and text. You will visit any web links found in the text and integrate
a summary with web citations, aiming for up to two citations explicitly returned in context as raw web hyperlinks.
Ensure to return web links as citations separated by new lines.
You should aim to select one or more of these topics in this form appropriate to the created summary,
embedding the topic in Logseq double square brackets once in the returned text.
"""

[github]
github_access_token = "default_github_token"
github_owner = "default_owner"
github_repo = "default_repo"
github_directory = "default_directory"

[ragflow]
ragflow_api_key = "default_ragflow_key"
ragflow_api_base_url = "http://192.168.0.51/v1/"

[perplexity]
perplexity_api_key = "default_perplexity_key"
perplexity_model = "llama-3.1-sonar-small-128k-online"
perplexity_api_url = "https://api.perplexity.ai/chat/completions"
perplexity_max_tokens = 4096
perplexity_temperature = 0.5
perplexity_top_p = 0.9
perplexity_presence_penalty = 0.0
perplexity_frequency_penalty = 1.0

[openai]
openai_api_key = "default_openai_key"
openai_base_url = "wss://api.openai.com/v1/realtime"

[default]
max_concurrent_requests = 5
max_retries = 3
retry_delay = 5
api_client_timeout = 30

[visualization]
node_color = "0x1A0B31"
edge_color = "0xff0000"
hologram_color = "0xFFD700"
node_size_scaling_factor = 3
hologram_scale = 5
hologram_opacity = 0.1
edge_opacity = 0.3
label_font_size = 36
fog_density = 0.002

# Physics simulation parameters
force_directed_iterations = 250
# Spring force (0.001-1.0)
force_directed_spring = 0.01
# Required for backend compatibility
force_directed_repulsion = 1000.0
force_directed_attraction = 0.01
# Damping (0.5-0.95)
force_directed_damping = 0.8

[bloom]
# Bloom settings for nodes
node_bloom_strength = 0.1
node_bloom_radius = 0.1
node_bloom_threshold = 0.0

# Bloom settings for edges
edge_bloom_strength = 0.2
edge_bloom_radius = 0.3
edge_bloom_threshold = 0.0

# Bloom settings for environmental elements
environment_bloom_strength = 0.5
environment_bloom_radius = 0.1
environment_bloom_threshold = 0.0

[fisheye]
enabled = false
strength = 0.5
focus_point = [0.0, 0.0, 0.0]
radius = 100.0
