# settings.toml

# Prompt for the AI assistant
prompt = """
You are an AI assistant building summaries of web links and text. You will visit any web links found in the text and integrate
a summary with web citations, aiming for up to two citations explicitly returned in context as raw web hyperlinks.
Ensure to return web links as citations separated by new lines.
You should aim to select one or more of these topics in this form appropriate to the created summary,
embedding the topic in Logseq double square brackets once in the returned text.
"""

# List of topics to embed in the summary
topics = [
    "Artificial Intelligence",
    "Machine Learning",
    "Rust Programming",
    "Web Development",
    "WebXR",
    "Three.js",
    "GPU Computing",
    "Graph Visualization",
    "Markdown Processing"
]

# Perplexity API configuration
[perplexity]
api_key = "your_actual_api_key"       # Replace with your actual API key
model = "test-model"                  # Model name, e.g., "test-model"
api_base_url = "http://mock-server.test"  # URL of the API endpoint or mock server
max_tokens = 100                      # Maximum number of tokens
temperature = 0.7                     # Sampling temperature
top_p = 0.9                           # Nucleus sampling parameter
presence_penalty = 0.0                # Presence penalty
frequency_penalty = 0.0               # Frequency penalty
