name: CI Pipeline

on:
  push:
    branches: [ feature-branch ]
  pull_request:
    branches: [ feature-branch ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: docker build -t my-app-test -f webxr-graph/Dockerfile.test ./webxr-graph
      
      - name: Run linting
        run: docker run my-app-test npm run lint
      
      - name: Run tests
        run: docker run my-app-test npm test

